/*
 This program was created by Dylan T
This program was created on March 23rd, 2018
It displays a discount amount and the discounted price if the purchase is $10.00 or over 
 */
import java.text.*; //Import java.text to the program which allows decimal format to be used

public class SuperStoreForm extends javax.swing.JFrame {
    
     DecimalFormat x = new DecimalFormat("##.00"); // Declaress a new decimal format called x and assigns it ##.00 
       
    public SuperStoreForm() {
        initComponents();  
   
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelSuperStoreSale = new javax.swing.JLabel();
        labelAmountofPurchases = new javax.swing.JLabel();
        textInputAmountofPurchases = new javax.swing.JTextField();
        labelDiscountAmount = new javax.swing.JLabel();
        textDiscountAmount = new javax.swing.JTextField();
        labelDiscountedPrice = new javax.swing.JLabel();
        textDiscountedPrice = new javax.swing.JTextField();
        buttonCalculate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelSuperStoreSale.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelSuperStoreSale.setText("Super Store Sale");

        labelAmountofPurchases.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelAmountofPurchases.setText("Amount of Purchases:");

        textInputAmountofPurchases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textInputAmountofPurchasesActionPerformed(evt);
            }
        });

        labelDiscountAmount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelDiscountAmount.setText("Discount Amount: ");

        textDiscountAmount.setEditable(false);
        textDiscountAmount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textDiscountAmount.setText("$0.00");
        textDiscountAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDiscountAmountActionPerformed(evt);
            }
        });

        labelDiscountedPrice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelDiscountedPrice.setText("Discounted Price:");

        textDiscountedPrice.setEditable(false);
        textDiscountedPrice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textDiscountedPrice.setText("$0.00");

        buttonCalculate.setText("Calculate");
        buttonCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCalculateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(labelSuperStoreSale))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDiscountAmount)
                            .addComponent(labelAmountofPurchases)
                            .addComponent(labelDiscountedPrice))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonCalculate)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(textInputAmountofPurchases)
                                .addComponent(textDiscountAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                                .addComponent(textDiscountedPrice)))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelSuperStoreSale)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAmountofPurchases)
                    .addComponent(textInputAmountofPurchases, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(buttonCalculate)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelDiscountAmount)
                    .addComponent(textDiscountAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDiscountedPrice)
                    .addComponent(textDiscountedPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textInputAmountofPurchasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textInputAmountofPurchasesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textInputAmountofPurchasesActionPerformed

    private void textDiscountAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDiscountAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDiscountAmountActionPerformed

    private void buttonCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCalculateActionPerformed
        double amountofPurchases, discountPrice, discountedPrice; // Declares double variable called amountOfPurchases, discountPrice anddiscountedPrice
        double amount = Double.parseDouble(textInputAmountofPurchases.getText());// Assigns the value of testfield to amount
        discountPrice = 0;// Assigns discountPrice = 0
        discountedPrice = 0;// Assigns discountedPrice = 0
        if (amount >= 10) // If amount is equal to or greater than 
            discountPrice = amount * 0.10; // discountPrice equals the amount times 0.10
        discountedPrice = amount - discountPrice; // discountedPrice equals amount - dicountPrice
        
           textDiscountAmount.setText("$" + x.format(discountPrice));// Sets text to textDiscountAmount textfield
           textDiscountedPrice.setText("$" + x.format(discountedPrice)); // Sets text to textDiscountedPrice textfield
        {
    }//GEN-LAST:event_buttonCalculateActionPerformed
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuperStoreForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuperStoreForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuperStoreForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuperStoreForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuperStoreForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCalculate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelAmountofPurchases;
    private javax.swing.JLabel labelDiscountAmount;
    private javax.swing.JLabel labelDiscountedPrice;
    private javax.swing.JLabel labelSuperStoreSale;
    private javax.swing.JTextField textDiscountAmount;
    private javax.swing.JTextField textDiscountedPrice;
    private javax.swing.JTextField textInputAmountofPurchases;
    // End of variables declaration//GEN-END:variables
}
